/**
 * 票据/文档类型注册表
 *
 * 数据来源：百度文字识别（OCR）官方 API 文档 https://ai.baidu.com/ai-doc/OCR/Ek3h7xypm
 * 每种类型包含：
 *   - type_code:        唯一编码
 *   - type_name:        显示名（小类）
 *   - category:         大类编码
 *   - category_display: 大类显示名
 *   - description:      描述
 *   - example_json:     JSON 示例（取各接口"返回示例"中 words_result 的内容，供大模型参考输出格式）
 *   - example_define:   字段说明（解释 example_json 中各字段的中文含义，来源于接口"返回参数"字段表）
 */

/** 单条票据类型定义 */
export interface ReceiptType {
  type_code: string;
  type_name: string;
  category: string;
  category_display: string;
  description: string;
  /** JSON 示例（对应百度 OCR 接口返回示例中 words_result 的内容） */
  example_json: string;
  /** example_json 中各字段的中文含义说明 */
  example_define: Record<string, string>;
}

/** 所有支持的票据/文档类型（按大类分组） */
export const RECEIPT_TYPES: ReceiptType[] = [
  // ===== 财税报销 =====
  {
    type_code: 'vat_invoice',
    type_name: '增值税发票',
    category: 'finance',
    category_display: '财税报销',
    description: '增值税专用发票、普通发票、电子发票、卷票、区块链发票',
    example_json: '{"InvoiceNumDigit":"123456","ServiceType":"其他","InvoiceNum":"14641426","InvoiceNumConfirm":"14641426","SellerName":"上海易火广告传媒有限公司","CommodityTaxRate":[{"word":"6%","row":"1"}],"SellerBank":"中国银行南翔支行446863841354","Checker":":沈园园","TotalAmount":"94339.62","CommodityAmount":[{"word":"94339.62","row":"1"}],"InvoiceDate":"2016年06月02日","CommodityTax":[{"word":"5660.38","row":"1"}],"PurchaserName":"百度时代网络技术(北京)有限公司","CommodityNum":[{"word":"","row":"1"}],"Province":"上海","City":"","SheetNum":"第三联","Agent":"否","PurchaserBank":"招商银行北京分行大屯路支行8661820285100030","Remarks":"告传","Password":"074/45781873408>/6>8>65*887676033/51+<5415>9/32--852>1+29<65>641-5>66<500>87/*-34<943359034>716905113*4242>","SellerAddress":":嘉定区胜辛南路500号15幢1161室55033753","PurchaserAddress":"北京市海淀区东北旺西路8号中关村软件园17号楼二属A2010-59108001","InvoiceCode":"3100153130","InvoiceCodeConfirm":"3100153130","CommodityUnit":[{"word":"","row":"1"}],"Payee":":徐蓉","PurchaserRegisterNum":"110108787751579","CommodityPrice":[{"word":"","row":"1"}],"NoteDrawer":"沈园园","AmountInWords":"壹拾万圆整","AmountInFiguers":"100000.00","TotalTax":"5660.38","InvoiceType":"专用发票","SellerRegisterNum":"913101140659591751","CommodityName":[{"word":"信息服务费","row":"1"}],"CommodityType":[{"word":"","row":"1"}],"CommodityPlateNum":[],"CommodityVehicleType":[],"CommodityStartDate":[],"CommodityEndDate":[],"OnlinePay":""}',
    example_define: {
      InvoiceNumDigit: '数电票号，仅纸质全电发票密码区输出',
      ServiceType: '发票消费类型：餐饮、电器设备、通讯、服务、日用品食品、医疗、交通、其他',
      InvoiceNum: '发票号码',
      InvoiceNumConfirm: '发票号码辅助校验码，一般业务场景可忽略',
      SellerName: '销售方名称',
      CommodityTaxRate: '税率',
      SellerBank: '销售方开户行及账号',
      Checker: '复核人',
      TotalAmount: '合计金额',
      CommodityAmount: '金额',
      InvoiceDate: '开票日期',
      CommodityTax: '税额',
      PurchaserName: '购方名称',
      CommodityNum: '数量',
      Province: '省',
      City: '市',
      SheetNum: '联次信息：第一联/第二联/第三联',
      Agent: '是否代开',
      PurchaserBank: '购方开户行及账号',
      Remarks: '备注',
      Password: '密码区',
      SellerAddress: '销售方地址及电话',
      PurchaserAddress: '购方地址及电话',
      InvoiceCode: '发票代码',
      InvoiceCodeConfirm: '发票代码辅助校验码，一般业务场景可忽略',
      CommodityUnit: '单位',
      Payee: '收款人',
      PurchaserRegisterNum: '购方纳税人识别号',
      CommodityPrice: '单价',
      NoteDrawer: '开票人',
      AmountInWords: '价税合计（大写）',
      AmountInFiguers: '价税合计（小写）',
      TotalTax: '合计税额',
      InvoiceType: '发票种类：普通发票、专用发票、电子普通发票、电子专用发票、通行费电子普票、区块链发票等',
      SellerRegisterNum: '销售方纳税人识别号',
      CommodityName: '货物名称',
      CommodityType: '规格型号',
      CommodityPlateNum: '车牌号，仅通行费增值税电子普通发票含有此参数',
      CommodityVehicleType: '车辆类型，仅通行费增值税电子普通发票含有此参数',
      CommodityStartDate: '通行日期起，仅通行费增值税电子普通发票含有此参数',
      CommodityEndDate: '通行日期止，仅通行费增值税电子普通发票含有此参数',
      OnlinePay: '电子支付标识，仅区块链发票含有此参数',
      word: '明细行文字内容',
      row: '明细行行号',
    },
  },
  {
    type_code: 'quota_invoice',
    type_name: '定额发票',
    category: 'finance',
    category_display: '财税报销',
    description: '各类定额发票',
    example_json: '{"invoice_code":"161034127200","invoice_number":"01275486","invoice_rate":"伍拾元整","invoice_rate_lowercase":"100.00","province":"陕西"}',
    example_define: {
      invoice_code: '发票代码',
      invoice_number: '发票号码',
      invoice_rate: '发票金额（大写）',
      invoice_rate_lowercase: '发票金额小写',
      province: '省',
    },
  },
  {
    type_code: 'machine_invoice',
    type_name: '通用机打发票',
    category: 'finance',
    category_display: '财税报销',
    description: '国家/地方税务局发行的通用机打发票',
    example_json: '{"City":"","InvoiceNum":"01445096","SellerName":"百度餐饮店","IndustrySort":"生活服务","Province":"广东省","CommodityAmount":[{"word":"183.00","row":"1"}],"InvoiceDate":"2020年07月28日","PurchaserName":"中信建投证券股份有限公司","CommodityNum":[],"InvoiceCode":"144001901511","CommodityUnit":[],"SheetNum":"","PurchaserRegisterNum":"9144223008453480X9","Time":"","CommodityPrice":[],"AmountInFiguers":"183.00","AmountInWords":"壹佰捌拾叁元整","CheckCode":"61042119820421061301","TotalTax":"183.00","InvoiceType":"广东通用机打发票","SellerRegisterNum":"61042119820421061301","CommodityName":[{"word":"餐费","row":"1"}]}',
    example_define: {
      InvoiceNum: '发票号码',
      SellerName: '销售方名称',
      IndustrySort: '行业分类',
      Province: '省',
      City: '市',
      CommodityAmount: '商品金额，明细行数组，每行含 word 与 row',
      InvoiceDate: '开票日期',
      PurchaserName: '购买方名称',
      CommodityNum: '商品数量，明细行数组',
      InvoiceCode: '发票代码',
      CommodityUnit: '商品单位，明细行数组',
      SheetNum: '联次',
      PurchaserRegisterNum: '购买方纳税人识别号',
      Time: '时间',
      CommodityPrice: '商品单价，明细行数组',
      AmountInFiguers: '合计金额（小写）',
      AmountInWords: '合计金额（大写）',
      CheckCode: '校验码',
      TotalTax: '合计税额',
      InvoiceType: '发票类型',
      SellerRegisterNum: '销售方纳税人识别号',
      CommodityName: '商品名称，明细行数组',
      word: '明细行文字内容',
      row: '明细行行号',
    },
  },
  {
    type_code: 'train_ticket',
    type_name: '火车票',
    category: 'finance',
    category_display: '财税报销',
    description: '大陆火车票',
    example_json: '{"id_num":"2302051998****156X","name":"裴一丽","ticket_rates":"￥54.5元","destination_station":"天津站","seat_category":"二等座","sales_station":"北京南","ticket_num":"F05706","seat_num":"02车03C号","time":"09:36","date":"2019年04月03日","serial_number":"10010300067846","train_num":"C255","starting_station":"北京南站"}',
    example_define: {
      id_num: '身份证号',
      name: '乘客姓名',
      ticket_rates: '车票金额',
      destination_station: '到达站',
      seat_category: '席别',
      sales_station: '售站',
      ticket_num: '车票号',
      seat_num: '座位号',
      time: '时间',
      date: '出发日期',
      serial_number: '序列号',
      train_num: '车次号',
      starting_station: '始发站',
    },
  },
  {
    type_code: 'taxi_receipt',
    type_name: '出租车票',
    category: 'finance',
    category_display: '财税报销',
    description: '全国各大城市出租车发票',
    example_json: '{"Date":"2017-11-26","Fare":"¥153.30元","Location":"北京","InvoiceCode":"111001681009","InvoiceNum":"90769610","TaxiNum":"BV2062","Time":"20:42-21:07","PickupTime":"20:42","DropoffTime":"21:07","FuelOilSurcharge":"¥1.00","CallServiceSurcharge":"¥1.00","TotalFare":"¥155.30元","Province":"北京","City":"北京市","PricePerkm":"2.50元/KM","Distance":"4.5KM"}',
    example_define: {
      Date: '日期',
      Fare: '金额',
      Location: '开票城市',
      InvoiceCode: '发票代码',
      InvoiceNum: '发票号码',
      TaxiNum: '车牌号',
      Time: '上下车时间',
      PickupTime: '上车时间',
      DropoffTime: '下车时间',
      FuelOilSurcharge: '燃油附加费',
      CallServiceSurcharge: '叫车服务费',
      TotalFare: '总金额',
      Province: '省',
      City: '市',
      PricePerkm: '单价',
      Distance: '里程',
    },
  },
  {
    type_code: 'air_ticket',
    type_name: '飞机行程单',
    category: 'finance',
    category_display: '财税报销',
    description: '飞机行程单（航空运输电子客票行程单）',
    example_json: '{"insurance":"20.00","date":"2019-10-22","allow":"20K","flight":"CA6589","issued_by":"中国国际航空服务有限公司","starting_station":"武汉","fare":"260.00","endorsement":"不得签转改期退转","ticket_rates":"350.00","ck":"5866","serial_number":"51523588676","ticket_number":"7843708871196","fuel_surcharge":"EXEMPT","carrier":"南航","issued_date":"2019-10-30","other_tax":"","fare_basis":"NREOW","id_num":"411201123909020877","destination_station":"合肥","name":"郭达","agent_code":"BJS19197300025","time":"21:25","class":"N","dev_fund":"50.00"}',
    example_define: {
      insurance: '保险费',
      date: '日期',
      allow: '免费行李',
      flight: '航班号',
      issued_by: '填开单位',
      starting_station: '始发站',
      fare: '票价',
      endorsement: '签注',
      ticket_rates: '合计金额',
      ck: '验证码',
      serial_number: '印刷序号',
      ticket_number: '电子客票号码',
      fuel_surcharge: '燃油附加费',
      carrier: '承运人',
      issued_date: '填开日期',
      other_tax: '其他税费',
      fare_basis: '客票级别',
      id_num: '身份证号',
      destination_station: '目的站',
      name: '姓名',
      agent_code: '销售单位号',
      time: '时间',
      class: '座位等级',
      dev_fund: '民航发展基金/机建费',
    },
  },
  {
    type_code: 'bus_ticket',
    type_name: '汽车票',
    category: 'finance',
    category_display: '财税报销',
    description: '全国范围汽车票',
    example_json: '{"DestinationStation":"郑州西站","IdNum":"424133********3014","Time":"08:30","InvoiceCode":"145021822522","InvoiceNum":"1450374239","StartingStation":"北京南站","Date":"2020-01-24","Name":"王文","Fare":"69.00"}',
    example_define: {
      DestinationStation: '到达站',
      IdNum: '身份证号',
      Time: '时间',
      InvoiceCode: '发票代码',
      InvoiceNum: '发票号码',
      StartingStation: '出发站',
      Date: '日期',
      Name: '姓名',
      Fare: '金额',
    },
  },
  {
    type_code: 'toll_invoice',
    type_name: '过路过桥费发票',
    category: 'finance',
    category_display: '财税报销',
    description: '过路、过桥费发票',
    example_json: '{"Entrance":"保定北","Time":"13:24","InvoiceCode":"237001473201","Date":"2020-02-18","Exit":"邯郸","Fare":"110.00","InvoiceNum":"95876669","City":"保定","Province":"河北"}',
    example_define: {
      Entrance: '入口',
      Time: '时间',
      InvoiceCode: '发票代码',
      Date: '日期',
      Exit: '出口',
      Fare: '金额',
      InvoiceNum: '发票号码',
      City: '市',
      Province: '省',
    },
  },
  {
    type_code: 'ferry_ticket',
    type_name: '船票',
    category: 'finance',
    category_display: '财税报销',
    description: '客运船票、货运船票',
    example_json: '{"InvoiceType":"客运船票","InvoiceCode":"111001681009","InvoiceNum":"90769610","StartingStation":"烟台","DestinationStation":"大连","InvoiceDate":"2020-10-26","Fare":"¥153.30元"}',
    example_define: {
      InvoiceType: '发票类型：客运船票/货运船票',
      InvoiceCode: '发票代码',
      InvoiceNum: '发票号码',
      StartingStation: '出发地点',
      DestinationStation: '到达地点',
      InvoiceDate: '开票日期',
      Fare: '总金额',
    },
  },
  {
    type_code: 'online_taxi',
    type_name: '网约车行程单',
    category: 'finance',
    category_display: '财税报销',
    description: '滴滴、高德等网约车行程单',
    example_json: '{"TotalFare":"2316","EndTime":"2020-07-30 19:00","Phone":"13000000000","ServiceProvider":"滴滴企业版","StartTime":"2020-07-01 16:00","ApplicationDate":"2017-12-08","ItemId":"3","items":[{"ItemId":"1","StartPlace":"鱼化寨地铁-D口","PickupTime":"16:00","CarType":"快车","City":"西安市","Distance":"9.7","PickupDate":"20-07-01","DestinationPlace":"创新港","Fare":"20.86"},{"ItemId":"2","StartPlace":"科学园东门","PickupTime":"14:56","CarType":"快车","City":"西安市","Distance":"91","PickupDate":"20-07-02","DestinationPlace":"鱼化寨地铁站","Fare":"18.58"},{"ItemId":"3","StartPlace":"中俄丝路创新园东门","PickupTime":"19:00","CarType":"快车","City":"西安市","Distance":"9.1","PickupDate":"20-07-30","DestinationPlace":"新门地铁站","Fare":"20.38"}]}',
    example_define: {
      TotalFare: '总金额',
      EndTime: '行程结束时间',
      Phone: '行程人手机号',
      ServiceProvider: '服务商（滴滴、高德等）',
      StartTime: '行程开始时间',
      ApplicationDate: '申请日期',
      ItemId: '行程信息中包含的行程数量',
      items: '行程明细数组',
      StartPlace: '起点',
      PickupTime: '上车时间',
      CarType: '车型',
      City: '城市',
      Distance: '里程',
      PickupDate: '上车日期',
      DestinationPlace: '终点',
      Fare: '金额',
    },
  },
  {
    type_code: 'shopping_receipt',
    type_name: '购物小票',
    category: 'finance',
    category_display: '财税报销',
    description: '商场、超市、药店购物小票',
    example_json: '[{"total_amount":[{"word":"5.50"}],"discount":[{"word":"0.8"}],"currency":[{"word":"RMB"}],"receipt_num":[{"word":"22202010230414"}],"shop_name":[{"word":"盛玛特购物中心"}],"consumption_time":[{"word":"16:18"}],"consumption_date":[{"word":"2020-10-23"}],"table_row_num":2,"table":[{"product":{"word":"仔姜2100871003105"},"quantity":{"word":"0.199"},"unit_price":{"word":"15.60"},"subtotal_amount":{"word":"3.10"}},{"product":{"word":"绿豆芽2100741001200"},"quantity":{"word":"0.469"},"unit_price":{"word":"2.56"},"subtotal_amount":{"word":"1.20"}},{"product":{"word":"魔芋2100776001206"},"quantity":{"word":"0.612"},"unit_price":{"word":"1.96"},"subtotal_amount":{"word":"1.20"}}],"paid_amount":[{"word":"5.50"}],"print_date":[{"word":"2022-01-01"}],"machine_num":[{"word":"22"}],"change":[{"word":""}],"employee_num":[{"word":"4004"}],"print_time":[{"word":""}]}]',
    example_define: {
      total_amount: '总金额',
      discount: '优惠/折扣',
      currency: '币种',
      receipt_num: '小票号码',
      shop_name: '店名/超市名字',
      consumption_time: '消费时间',
      consumption_date: '消费日期',
      table_row_num: '商品明细行数',
      table: '消费明细数组',
      product: '商品条码/名称',
      quantity: '数量',
      unit_price: '单价',
      subtotal_amount: '小计金额',
      paid_amount: '实收金额',
      print_date: '打印日期',
      machine_num: '机器编号',
      change: '找零',
      employee_num: '工号',
      print_time: '打印时间',
      word: '字段识别结果文本',
    },
  },
  {
    type_code: 'bank_receipt',
    type_name: '银行回单',
    category: 'finance',
    category_display: '财税报销',
    description: '各大银行回单',
    example_json: '{"标题":[{"word":"中国工商银行网上银行电子回单"}],"付款人户名":[{"word":"北京小度网络科技有限公司"}],"付款人开户银行":[{"word":"北京开发区支行营业室"}],"付款人账号":[{"word":"3208095919200208008"}],"收款人户名":[{"word":"上海小度网络科技有限公司"}],"收款人开户银行":[{"word":"工行前海支行"}],"收款人账号":[{"word":"3707020802702372707"}],"大写金额":[{"word":"人民币壹万陆仟贰佰叁拾玖元叁角"}],"小写金额":[{"word":"￥16239.30元"}],"流水号":[{"word":"27208770"}],"回单编号":[{"word":"2085758711703264"}],"交易日期":[{"word":""}],"摘要":[{"word":"货款"}],"用途":[{"word":""}]}',
    example_define: {
      '标题': '回单标题，如"中国工商银行网上银行电子回单"',
      '付款人户名': '付款人户名',
      '付款人开户银行': '付款人开户银行',
      '付款人账号': '付款人账号',
      '收款人户名': '收款人户名',
      '收款人开户银行': '收款人开户银行',
      '收款人账号': '收款人账号',
      '大写金额': '金额（大写）',
      '小写金额': '金额（小写）',
      '流水号': '流水号',
      '回单编号': '回单编号',
      '交易日期': '交易日期',
      '摘要': '摘要',
      '用途': '用途',
      word: '字段识别结果文本',
    },
  },

  // ===== 交通出行 =====
  {
    type_code: 'license_plate',
    type_name: '车牌',
    category: 'traffic',
    category_display: '交通出行',
    description: '机动车车牌（蓝牌、绿牌、单/双行黄牌）',
    example_json: '[{"color":"blue","number":"京KBT355","probability":[0.9999992847,0.999999404,0.9999910593,0.9999765158,0.999994874,0.9998959303,0.9999984503],"vertexes_location":[{"x":495,"y":589},{"x":800,"y":587},{"x":800,"y":676},{"x":496,"y":678}]}]',
    example_define: {
      color: '车牌颜色：blue（蓝）、green（绿）、yellow（黄）、white（白）、black（黑）、yellow_green（新能源大型汽车黄绿车牌）、penyin（大货车喷印车牌）、unknow（未知）',
      number: '车牌号码',
      probability: '车牌中每个字符的置信度数组（从左往右），区间 0-1',
      vertexes_location: '文字外接多边形顶点位置数组',
      x: '水平坐标（坐标 0 点为左上角）',
      y: '垂直坐标（坐标 0 点为左上角）',
    },
  },
  {
    type_code: 'vin_code',
    type_name: 'VIN码',
    category: 'traffic',
    category_display: '交通出行',
    description: '车辆识别代号（车架号）',
    example_json: '[{"location":{"left":124,"top":11,"width":58,"height":359},"words":"LFV2A11K8D4010942"}]',
    example_define: {
      location: 'VIN 码位置数组（坐标 0 点为左上角）',
      left: '定位矩形左上顶点的水平坐标',
      top: '定位矩形左上顶点的垂直坐标',
      width: '定位矩形的宽度',
      height: '定位矩形的高度',
      words: 'VIN 码识别结果',
    },
  },
  {
    type_code: 'driving_license',
    type_name: '驾驶证',
    category: 'traffic',
    category_display: '交通出行',
    description: '机动车驾驶证（正本/副本）',
    example_json: '{"姓名":{"words":"万万"},"记录":{"words":"请于每个记分周期结束后三十日接受审验。无记分的，免予本次审验。"},"证号":{"words":"513601198209290000"},"档案编号":{"words":"511600001169"}}',
    example_define: {
      '姓名': '驾驶人姓名',
      '记录': '审验记录',
      '证号': '驾驶证号',
      '档案编号': '档案编号',
      words: '字段识别结果文本',
    },
  },
  {
    type_code: 'vehicle_license',
    type_name: '行驶证',
    category: 'traffic',
    category_display: '交通出行',
    description: '机动车行驶证（主页及副页）',
    example_json: '{"强制报废期止":{"words":"20391025"},"车身颜色":{"words":"绿"},"能源种类":{"words":"柴油"},"住址":{"words":"河北省邯郸市邯山区马头工业城杜村九组"},"发证机关":{"words":"河北省邯郸市公安局交通巡逻警察支队"},"核定载质量":{"words":"9925kg"},"整备质量":{"words":"7880kg"},"外廓尺寸":{"words":"6180X2350X2850mm"},"核定载人数":{"words":""},"总质量":{"words":"18000kg"},"准牵引总质量":{"words":""},"备注":{"words":""}}',
    example_define: {
      '强制报废期止': '强制报废期止（副页）',
      '车身颜色': '车身颜色',
      '能源种类': '能源种类',
      '住址': '所有人住址',
      '发证机关': '发证机关',
      '核定载质量': '核定载质量',
      '整备质量': '整备质量',
      '外廓尺寸': '外廓尺寸',
      '核定载人数': '核定载人数',
      '总质量': '总质量',
      '准牵引总质量': '准牵引总质量',
      '备注': '备注',
      words: '字段识别结果文本',
    },
  },
  {
    type_code: 'vehicle_invoice',
    type_name: '机动车销售发票',
    category: 'traffic',
    category_display: '交通出行',
    description: '机动车销售统一发票',
    example_json: '{"InvoiceNum":"00875336","Saler":"深圳市新能源汽车销售有限公司","LimitPassenger":"5","MachineCode":"669745967911","VinNum":"LJLGTCRP1J4007581","TaxRate":"16%","PriceTaxLow":"106100.00","InvoiceDate":"2018-11-29","Price":"￥91465.52","SalerBank":"中国工商银行股份有限公司深圳岭园支行","TaxAuthor":"国家锐务总局深圳市龙岗区税务局第五税务所","ManuModel":"江淮牌HFC7007EYBD6","CertificateNum":"WCH0794J0976801","Purchaser":"苏子潇","VehicleType":"纯电动轿车","InvoiceCode":"14975047560","PriceTax":"壹拾万陆仟壹佰圆整","SalerPhone":"0755-83489306","SalerAddress":"深圳市龙岗区龙岗街道百世国际汽车城","Origin":"安徽省合肥市","EngineNum":"18958407","Tax":"14634.48","PurchaserCode":"5135934475603742222","TaxAuthorCode":"14037589413","SalerAccountNum":"中国工商银行股份有限公司深圳岭园支行","SalerCode":"9144928346458292278H"}',
    example_define: {
      InvoiceNum: '发票号码',
      Saler: '销货单位名称',
      LimitPassenger: '限乘人数',
      MachineCode: '机器编号',
      VinNum: '车架号码',
      TaxRate: '税率',
      PriceTaxLow: '价税合计（小写）',
      InvoiceDate: '开票日期',
      Price: '不含税价格',
      SalerBank: '销货单位开户银行',
      TaxAuthor: '主管税务机关',
      ManuModel: '厂牌型号',
      CertificateNum: '合格证号',
      Purchaser: '购买方名称',
      VehicleType: '车辆类型',
      InvoiceCode: '发票代码',
      PriceTax: '价税合计（大写）',
      SalerPhone: '销货单位电话',
      SalerAddress: '销货单位地址',
      Origin: '产地',
      EngineNum: '发动机号码',
      Tax: '税额',
      PurchaserCode: '购买方身份证号码/组织机构代码',
      TaxAuthorCode: '主管税务机关代码',
      SalerAccountNum: '销货单位账号',
      SalerCode: '销货单位纳税人识别号',
    },
  },
  {
    type_code: 'vehicle_certificate',
    type_name: '车辆合格证',
    category: 'traffic',
    category_display: '交通出行',
    description: '车辆合格证',
    example_json: '{"ManufactureDate":"2016年10月13日","CarColor":"红","LimitPassenger":"2","EngineType":"WP12.460E50","TotalWeight":"25000","Power":"338","CertificationNo":"WEK29JX98645437","FuelType":"汽油","Manufacturer":"陕西汽车集团有限责任公司","SteeringType":"方向盘","Wheelbase":"3175+1350","SpeedLimit":"105","EngineNo":"1418K129178","SaddleMass":"8600","AxleNum":"3","CarModel":"SX4250MC4","VinNo":"LZGJHYD83JX197344","CarBrand":"陕汽牌","EmissionStandard":"GB17691-2005国V,GB3847-2005","Displacement":"11596","CertificateDate":"2018年11月28日","CarName":"牵引汽车","TyreNum":"10","ChassisID":"","ChassisModel":"","SeatingCapacity":"5","QualifySeal":"1","CGSSeal":"0"}',
    example_define: {
      ManufactureDate: '车辆制造日期',
      CarColor: '车身颜色',
      LimitPassenger: '驾驶室准乘人数',
      EngineType: '发动机型号',
      TotalWeight: '总质量',
      Power: '功率',
      CertificationNo: '合格证编号',
      FuelType: '燃料种类',
      Manufacturer: '车辆制造企业名',
      SteeringType: '转向形式',
      Wheelbase: '轴距',
      SpeedLimit: '最高设计车速',
      EngineNo: '发动机号',
      SaddleMass: '整备质量',
      AxleNum: '轴数',
      CarModel: '车辆型号',
      VinNo: '车架号',
      CarBrand: '车辆品牌',
      EmissionStandard: '排放标准',
      Displacement: '排量',
      CertificateDate: '发证日期',
      CarName: '车辆名称',
      TyreNum: '轮胎数',
      ChassisID: '底盘ID',
      ChassisModel: '底盘型号',
      SeatingCapacity: '额定载客人数',
      QualifySeal: '合格印章：1 有 / 0 无',
      CGSSeal: 'CGS 印章：1 有 / 0 无',
    },
  },
  {
    type_code: 'used_vehicle_invoice',
    type_name: '二手车销售发票',
    category: 'traffic',
    category_display: '交通出行',
    description: '二手车销售统一发票',
    example_json: '{"TransferVehicleManagementOffice":{"word":"车管所"},"ManuModel":{"word":"森林人JF1SH999"},"RegistrationCode":{"word":"320008998998"},"TotalCarPriceLow":{"word":"￥88000.00"},"TaxAddress":{"word":"苏州高新区"},"PurchaserCode":{"word":"313502198402043055"},"Saler":{"word":"春春"},"TaxCode":{"word":"74881478982966442866"},"Purchaser":{"word":"丽丽"},"InvoiceCode":{"word":"022001900539"},"InvoiceDate":{"word":"2020-05-13"},"SalerAddress":{"word":"江苏省苏州市工业园区"},"SalerCode":{"word":"4124524199001156900"},"TaxPhone":{"word":"12282680332"},"TaxNum":{"word":"91330505MW1NCQUQWE"},"PurchaserPhone":{"word":"0"},"VehicleType":{"word":"小型越野客车"},"LicensePlateNum":{"word":"苏U1A555"},"SheetNum":{"word":"二"},"VinNum":{"word":"JJ1SH95F4AG098838"},"TotalCarPrice":{"word":"捌万捌仟圆整"},"PurchaserAddress":{"word":"江苏省苏州市"},"SalerPhone":{"word":"0"},"UsedCarMarket":{"word":"苏州二手车电子商务有限公司"},"InvoiceNum":{"word":"00354542"}}',
    example_define: {
      TransferVehicleManagementOffice: '转入地车管所名称',
      ManuModel: '厂牌型号',
      RegistrationCode: '登记证号',
      TotalCarPriceLow: '车价合计（小写）',
      TaxAddress: '纳税人地址',
      PurchaserCode: '买方身份证号',
      Saler: '卖方',
      TaxCode: '税控码',
      Purchaser: '买方',
      InvoiceCode: '发票代码',
      InvoiceDate: '开票日期',
      SalerAddress: '卖方地址',
      SalerCode: '卖方身份证号',
      TaxPhone: '纳税人电话',
      TaxNum: '纳税人识别号',
      PurchaserPhone: '买方电话',
      VehicleType: '车辆类型',
      LicensePlateNum: '车牌号',
      SheetNum: '联次',
      VinNum: '车架号',
      TotalCarPrice: '车价合计（大写）',
      PurchaserAddress: '买方地址',
      SalerPhone: '卖方电话',
      UsedCarMarket: '二手车市场',
      InvoiceNum: '发票号码',
      word: '字段识别结果文本',
    },
  },

  // ===== 资质证照 =====
  {
    type_code: 'idcard',
    type_name: '身份证',
    category: 'card',
    category_display: '资质证照',
    description: '二代居民身份证（正反面）',
    example_json: '{"住址":{"words":"南京市江宁区弘景大道3889号"},"公民身份号码":{"words":"330881199904173914"},"出生":{"words":"19990417"},"姓名":{"words":"伍云龙"},"性别":{"words":"男"},"民族":{"words":"汉"}}',
    example_define: {
      '住址': '住址',
      '公民身份号码': '身份证号码',
      '出生': '出生日期',
      '姓名': '姓名',
      '性别': '性别',
      '民族': '民族',
      words: '字段识别结果文本',
    },
  },
  {
    type_code: 'bankcard',
    type_name: '银行卡',
    category: 'card',
    category_display: '资质证照',
    description: '各类银行卡',
    example_json: '{"bank_card_number":"3568 8900 8000 0005","valid_date":"07/21","bank_card_type":2,"bank_name":"招商银行","holder_name":"MR.CHENTA"}',
    example_define: {
      bank_card_number: '银行卡卡号',
      valid_date: '有效期',
      bank_card_type: '银行卡类型：0 不能识别 / 1 借记卡 / 2 贷记卡 / 3 准贷记卡 / 4 预付费卡',
      bank_name: '银行名，不能识别时为空',
      holder_name: '持卡人姓名，不能识别时为空',
    },
  },
  {
    type_code: 'business_license',
    type_name: '营业执照',
    category: 'card',
    category_display: '资质证照',
    description: '各类版式营业执照',
    example_json: '{"经营范围":{"words":"商务服务业"},"组成形式":{"words":"无"},"法人":{"words":"方平"},"证件编号":{"words":"921MA190538210301"},"注册资本":{"words":"200万元"},"单位名称":{"words":"有限公司"},"有效期":{"words":"长期"},"社会信用代码":{"words":"10440119MA06M85"},"实收资本":{"words":"无"},"有效期起始日期":{"words":"2019年01月01日"},"核准日期":{"words":"2019年01月01日"},"成立日期":{"words":"2019年01月01日"},"税务登记号":{"words":"无"},"地址":{"words":"广州市"},"登记机关":{"words":"无"},"类型":{"words":"有限责任公司(自然人投资或控股)"}}',
    example_define: {
      '经营范围': '经营范围',
      '组成形式': '组成形式',
      '法人': '法定代表人',
      '证件编号': '证件编号',
      '注册资本': '注册资本',
      '单位名称': '单位名称',
      '有效期': '有效期',
      '社会信用代码': '统一社会信用代码',
      '实收资本': '实收资本',
      '有效期起始日期': '有效期起始日期',
      '核准日期': '核准日期',
      '成立日期': '成立日期',
      '税务登记号': '税务登记号',
      '地址': '地址',
      '登记机关': '登记机关',
      '类型': '类型',
      words: '字段识别结果文本',
    },
  },
  {
    type_code: 'passport',
    type_name: '护照',
    category: 'card',
    category_display: '资质证照',
    description: '中国大陆居民护照（资料页）',
    example_json: '{"护照类型":{"words":"P"},"国家码":{"words":"CHN"},"护照签发地点":{"words":"山东/SHANDONG"},"MRZCode2":{"words":"E898657303CHNSDMO7O2<<<<<<<<<<<<<"},"有效期至":{"words":"20261004"},"签发机关":{"words":"出入境管理局"},"MRZCode1":{"words":"PONSUN<<JIAJIA<<<<<<<<<<<<<<<<<<<<<<<<<<"},"护照号码":{"words":"E89865730"},"签发日期":{"words":"20161005"},"出生地点":{"words":"山东/SHANDONG"},"姓名":{"words":"孙嘉佳"},"姓名拼音":{"words":"SUN,JIAJIA"},"国籍":{"words":"中国/CHINESE"},"生日":{"words":"19950723"},"性别":{"words":"男/M"}}',
    example_define: {
      '护照类型': '护照类型',
      '国家码': '国家码',
      '护照签发地点': '签发地点',
      'MRZCode2': '机读码第二行',
      '有效期至': '有效期至',
      '签发机关': '签发机关',
      'MRZCode1': '机读码第一行',
      '护照号码': '护照号码',
      '签发日期': '签发日期',
      '出生地点': '出生地点',
      '姓名': '姓名',
      '姓名拼音': '姓名拼音',
      '国籍': '国籍',
      '生日': '出生日期',
      '性别': '性别',
      words: '字段识别结果文本',
    },
  },
  {
    type_code: 'hk_macao_tw_pass',
    type_name: '港澳台证件',
    category: 'card',
    category_display: '资质证照',
    description: '港澳通行证、台湾通行证、台胞证、返乡证',
    example_json: '{"card_number":[{"word":"C00000000"}],"name_chn":[{"word":"证件样本"}],"name_eng":[{"word":"ZHENGJIAN,YANGBEN"}],"birthday":[{"word":"1981.08.03"}],"sex":[{"word":"女"}],"valid_date":[{"word":"2014.04.21-2024.04.20"}],"issue_authority":[{"word":"公安部出入境管理局"}],"issue_place":[{"word":"广东"}],"MRZCode":[{"word":"CSC000000004<2404200<8108038<6"}]}',
    example_define: {
      card_number: '证件号码',
      name_chn: '姓名',
      name_eng: '姓名（英文）',
      birthday: '出生日期',
      sex: '性别',
      valid_date: '有效期限',
      issue_authority: '签发机关',
      issue_place: '签发地点',
      MRZCode: '证件下方机读码',
      word: '字段识别结果文本',
    },
  },
  {
    type_code: 'household_register',
    type_name: '户口本',
    category: 'card',
    category_display: '资质证照',
    description: '居民户口簿',
    example_json: '{"Nation":{"words":"汉族"},"Sex":{"words":"女"},"Birthday":{"words":"1994年7月27日"},"Date":{"words":"2017年7月27日"},"BirthAddress":{"words":"四川省"},"Name":{"words":"王燕"},"FormerName":{"words":"王佳"},"HouseholdNum":{"words":"000007670"},"WWToCity":{"words":"由久居"},"WWHere":{"words":"1994年07月27日因出生迁来"},"CardNo":{"words":"112102199407273123"},"Education":{"words":"初中毕业"},"Relationship":{"words":"独生女"},"Height":{"words":"170厘米"},"Career":{"words":"无"},"WorkAddress":{"words":"无"},"Hometown":{"words":"四川省"},"OtherAddress":{"words":"四川省乐山市"},"Belief":{"words":"佛教"},"BloodType":{"words":"A型"},"MaritalStatus":{"words":"未婚"},"VeteranStatus":{"words":"无"}}',
    example_define: {
      Nation: '民族',
      Sex: '性别',
      Birthday: '生日',
      Date: '登记日期',
      BirthAddress: '出生地',
      Name: '姓名',
      FormerName: '曾用名',
      HouseholdNum: '户号',
      WWToCity: '何时由何地迁来本市（县）',
      WWHere: '何时由何地迁往本址',
      CardNo: '身份证号',
      Education: '文化程度',
      Relationship: '户主或与户主关系',
      Height: '身高',
      Career: '职业',
      WorkAddress: '服务处所',
      Hometown: '籍贯',
      OtherAddress: '本市（县）其他住址',
      Belief: '宗教信仰',
      BloodType: '血型',
      MaritalStatus: '婚姻状况',
      VeteranStatus: '兵役状况',
      words: '字段识别结果文本',
    },
  },
  {
    type_code: 'birth_certificate',
    type_name: '出生证明',
    category: 'card',
    category_display: '资质证照',
    description: '出生医学证明',
    example_json: '{"BirthProvince":{"words":"山东"},"BirthWeight":{"words":"3450克"},"MotherNationality":{"words":"中国"},"FatherAddress":{"words":"山东省青岛市"},"MotherEthnic":{"words":"汉族"},"MotherAddress":{"words":"山东省青岛市"},"Code":{"words":"U370073333"},"BabySex":{"words":"女"},"BirthCounty":{"words":"黄岛区"},"BabyBirthday":{"words":"2020年06月19日17时00分"},"BabyName":{"words":"安琪"},"FatherAge":{"words":"30岁"},"FatherEthnic":{"words":"汉族"},"MotherName":{"words":"田田"},"MotherID":{"words":"370284199509086021"},"BirthLength":{"words":"50厘米"},"GestationalAge":{"words":"41+1周"},"BirthCity":{"words":"青岛"},"MotherAge":{"words":"25岁"},"Hospital":{"words":"青岛市黄岛区医院"},"FatherNationality":{"words":"中国"},"FatherID":{"words":"370284199207126034"},"FatherName":{"words":"王军"}}',
    example_define: {
      BirthProvince: '出生地点_省',
      BirthWeight: '出生体重',
      MotherNationality: '母亲国籍',
      FatherAddress: '父亲住址',
      MotherEthnic: '母亲民族',
      MotherAddress: '母亲地址',
      Code: '出生证编号',
      BabySex: '性别',
      BirthCounty: '出生地点_县（区）',
      BabyBirthday: '出生时间',
      BabyName: '姓名',
      FatherAge: '父亲年龄',
      FatherEthnic: '父亲民族',
      MotherName: '母亲姓名',
      MotherID: '母亲身份证号',
      BirthLength: '出生身长',
      GestationalAge: '出生孕周',
      BirthCity: '出生地点_市',
      MotherAge: '母亲年龄',
      Hospital: '出生医院/医疗机构名称',
      FatherNationality: '父亲国籍',
      FatherID: '父亲身份证号',
      FatherName: '父亲姓名',
      words: '字段识别结果文本',
    },
  },
  {
    type_code: 'marriage_certificate',
    type_name: '结婚证',
    category: 'card',
    category_display: '资质证照',
    description: '结婚证',
    example_json: '{"姓名_男":[{"word":"李佑"}],"身份证件号_男":[{"word":"433024197905103103"}],"出生日期_男":[{"word":"1979-05-10"}],"国籍_男":[{"word":"中国"}],"性别_男":[{"word":"男"}],"姓名_女":[{"word":"刘美"}],"身份证件号_女":[{"word":"433024197609160160"}],"出生日期_女":[{"word":"1976-09-16"}],"国籍_女":[{"word":"中国"}],"性别_女":[{"word":"女"}],"结婚证字号":[{"word":"怀溆结字011004100号"}],"持证人":[{"word":"李佑"}],"备注":[{"word":""}],"登记日期":[{"word":"2010-06-10"}]}',
    example_define: {
      '姓名_男': '男方姓名',
      '身份证件号_男': '男方身份证件号',
      '出生日期_男': '男方出生日期',
      '国籍_男': '男方国籍',
      '性别_男': '男方性别',
      '姓名_女': '女方姓名',
      '身份证件号_女': '女方身份证件号',
      '出生日期_女': '女方出生日期',
      '国籍_女': '女方国籍',
      '性别_女': '女方性别',
      '结婚证字号': '结婚证字号',
      '持证人': '持证人',
      '备注': '备注',
      '登记日期': '登记日期',
      word: '字段识别结果文本',
    },
  },
  {
    type_code: 'divorce_certificate',
    type_name: '离婚证',
    category: 'card',
    category_display: '资质证照',
    description: '离婚证',
    example_json: '{"姓名_男":[{"word":"李佑"}],"身份证件号_男":[{"word":"433024197905103103"}],"出生日期_男":[{"word":"1979年05月10日"}],"国籍_男":[{"word":"中国"}],"性别_男":[{"word":"男"}],"姓名_女":[{"word":"刘美"}],"身份证件号_女":[{"word":"433024197609160160"}],"出生日期_女":[{"word":"1976年09月16日"}],"国籍_女":[{"word":"中国"}],"性别_女":[{"word":"女"}],"离婚证字号":[{"word":"L010101-1020-001111"}],"持证人":[{"word":"李佑"}],"备注":[{"word":"备注"}],"登记日期":[{"word":"2010年06月10日"}]}',
    example_define: {
      '姓名_男': '男方姓名',
      '身份证件号_男': '男方身份证件号',
      '出生日期_男': '男方出生日期',
      '国籍_男': '男方国籍',
      '性别_男': '男方性别',
      '姓名_女': '女方姓名',
      '身份证件号_女': '女方身份证件号',
      '出生日期_女': '女方出生日期',
      '国籍_女': '女方国籍',
      '性别_女': '女方性别',
      '离婚证字号': '离婚证字号',
      '持证人': '持证人',
      '备注': '备注',
      '登记日期': '登记日期',
      word: '字段识别结果文本',
    },
  },
  {
    type_code: 'house_property',
    type_name: '房产证',
    category: 'card',
    category_display: '资质证照',
    description: '不动产权证书（房产证）',
    example_json: '{"权利人":[{"word":"阮兴武"}],"坐落":[{"word":"吉水县乌江镇前江村丰山组"}],"权利类型":[{"word":"宅基地使用权/房屋(构筑物)所有权"}],"面积":[{"word":"土地使用权面积:115.720㎡/房屋建筑面积:298.520㎡"}],"字第号":[{"word":"0042537"}],"不动产单元号":[{"word":"360822"}],"共有情况":[{"word":"家庭成员共有"}],"用途":[{"word":"农村宅基地/住宅"}],"使用期限":[{"word":""}],"登记日期":[{"word":""}],"共有人":[{"word":""}]}',
    example_define: {
      '权利人': '权利人',
      '坐落': '坐落',
      '权利类型': '权利类型',
      '面积': '面积',
      '字第号': '字第号',
      '不动产单元号': '不动产单元号',
      '共有情况': '共有情况',
      '用途': '用途',
      '使用期限': '使用期限',
      '登记日期': '登记日期',
      '共有人': '共有人',
      word: '字段识别结果文本',
    },
  },
  {
    type_code: 'social_security_card',
    type_name: '社保卡',
    category: 'card',
    category_display: '资质证照',
    description: '社会保障卡',
    example_json: '{"sex":{"word":"男"},"birth_date":{"word":"1993年6月16日"},"issue_date":{"word":""},"name":{"word":"徐乐"},"card_number":{"word":"122932663447"},"bank_card_number":{"word":""},"expiry_date":{"word":""},"social_security_number":{"word":"130201199306168223"}}',
    example_define: {
      sex: '性别',
      birth_date: '出生日期',
      issue_date: '签发日期',
      name: '姓名',
      card_number: '卡号',
      bank_card_number: '银行卡号',
      expiry_date: '有效期限',
      social_security_number: '社会保障卡号',
      word: '字段识别结果文本',
    },
  },

  // ===== 医疗健康 =====
  // TODO: 暂时屏蔽医疗健康类识别能力
  /*
  {
    type_code: 'medical_invoice',
    type_name: '医疗发票',
    category: 'medical',
    category_display: '医疗健康',
    description: '门诊/住院发票',
    example_json: '{"发票号":"12345678","姓名":"张三","性别":"男","金额小写":"1000.00","收款单位":"XX医院","医保统筹支付":"800.00","自费金额":"200.00"}',
  },
  {
    type_code: 'medical_detail',
    type_name: '医疗费用明细',
    category: 'medical',
    category_display: '医疗健康',
    description: '医疗费用明细清单',
    example_json: '{"姓名":"张三","日期":"2026年01月01日","总金额":"500.00","明细项目":[{"项目类型":"药品费","项目名称":"阿莫西林","单价":"10.00","数量":"3","金额":"30.00"}]}',
  },
  {
    type_code: 'medical_statement',
    type_name: '费用结算单',
    category: 'medical',
    category_display: '医疗健康',
    description: '医疗费用结算单',
    example_json: '{"姓名":"张三","入院时间":"2026年01月01日","出院时间":"2026年01月10日","发票总金额":"10000.00","自费金额":"2000.00","医保支付金额":"8000.00"}',
  },
  {
    type_code: 'medical_report',
    type_name: '检验报告单',
    category: 'medical',
    category_display: '医疗健康',
    description: '医疗检验报告单',
    example_json: '{"姓名":"张三","医院名称":"XX医院","报告单名称":"血常规检验报告","检查项目":[{"项目名称":"白细胞计数","结果":"6.5","单位":"10^9/L","参考区间":"3.5-9.5"}]}',
  },
  {
    type_code: 'medical_diagnosis',
    type_name: '诊断报告单',
    category: 'medical',
    category_display: '医疗健康',
    description: '医疗诊断报告单',
    example_json: '{"医院名称":"XX医院","报告名称":"CT诊断报告","姓名":"张三","检查部位":"胸部","检查提示":"未见明显异常"}',
  },
  {
    type_code: 'medical_record_home',
    type_name: '病案首页',
    category: 'medical',
    category_display: '医疗健康',
    description: '病案首页',
    example_json: '{"病案号":"BA202501010001","姓名":"张三","性别":"男","入院科别":"内科","出院科别":"内科","住院次数":"1"}',
  },
  {
    type_code: 'discharge_summary',
    type_name: '出院小结',
    category: 'medical',
    category_display: '医疗健康',
    description: '出院小结',
    example_json: '{"科室":"内科","姓名":"张三","入院日期":"2026年01月01日","出院日期":"2026年01月10日","入院诊断":"上呼吸道感染","出院医嘱":"注意休息"}',
  },
  */

  // ===== 教育培训 =====
  // TODO: 暂时屏蔽教育培训类识别能力
  /*
  {
    type_code: 'exam_analysis',
    type_name: '试卷分析',
    category: 'education',
    category_display: '教育培训',
    description: '作业、试卷分析',
    example_json: '{"words_result":[{"type":"title","words":"2025-2026学年第一学期期末考试"},{"type":"text","words":"第一题 选择题..."}]}',
  },
  {
    type_code: 'exam_cut',
    type_name: '试卷切题',
    category: 'education',
    category_display: '教育培训',
    description: '试卷题目切分识别',
    example_json: '{"题目":[{"题号":"1","题型":"选择题","题干":"下列哪个是中国的首都？","选项":["A. 上海","B. 北京","C. 广州","D. 深圳"],"答案":"B"}]}',
  },
  */

  // ===== 通用识别 =====
  // TODO: 暂时屏蔽通用识别类
  /*
  {
    type_code: 'general_basic',
    type_name: '通用文字识别',
    category: 'general',
    category_display: '通用识别',
    description: '通用文字识别',
    example_json: '{"words_result":[{"words":"百度OCR"},{"words":"高效准确"}]}',
  },
  {
    type_code: 'accurate_basic',
    type_name: '高精度识别',
    category: 'general',
    category_display: '通用识别',
    description: '高精度文字识别',
    example_json: '{"words_result":[{"words":"百度OCR","probability":0.999}]}',
  },
  {
    type_code: 'table_ocr',
    type_name: '表格识别',
    category: 'general',
    category_display: '通用识别',
    description: '表格文字识别',
    example_json: '{"table_count":1,"tables":[{"header":[{"word":"姓名"}],"body":[{"word":"张三"}]}]}',
  },
  {
    type_code: 'qrcode',
    type_name: '二维码识别',
    category: 'general',
    category_display: '通用识别',
    description: '二维码/条形码识别',
    example_json: '{"codes_result":[{"type":"qrcode","text":"https://www.baidu.com"}]}',
  },
  {
    type_code: 'seal',
    type_name: '印章识别',
    category: 'general',
    category_display: '通用识别',
    description: '印章检测识别',
    example_json: '{"words_result":[{"words":"北京XX科技有限公司","probability":0.99}]}',
  },
  */

  // ===== 其他场景 =====
  // TODO: 暂时屏蔽其他场景类识别能力
  /*
  {
    type_code: 'meter',
    type_name: '仪器仪表盘读数',
    category: 'other',
    category_display: '其他场景',
    description: '血糖仪、血压仪等读数',
    example_json: '{"readings":[{"value":"120","label":"高压"},{"value":"80","label":"低压"}]}',
  },
  {
    type_code: 'door_plate',
    type_name: '门脸文字',
    category: 'other',
    category_display: '其他场景',
    description: '店铺门脸文字',
    example_json: '{"texts":[{"text":"星巴克咖啡"}]}',
  },
  */
];

/** 按 type_code 查找类型定义 */
export function findReceiptType(typeCode: string): ReceiptType | undefined {
  return RECEIPT_TYPES.find((t) => t.type_code === typeCode);
}

/** 获取所有大类列表（去重） */
export function getCategories(): { category: string; category_display: string }[] {
  const map = new Map<string, string>();
  for (const t of RECEIPT_TYPES) {
    if (!map.has(t.category)) {
      map.set(t.category, t.category_display);
    }
  }
  return Array.from(map.entries()).map(([category, category_display]) => ({ category, category_display }));
}

/** 按大类获取该类下所有小类 */
export function getTypesByCategory(category: string): ReceiptType[] {
  return RECEIPT_TYPES.filter((t) => t.category === category);
}